### PR TITLE
Fix: Add ability to apply scroll prompt to blocks and components (fixes #9)

### LINKED ISSUE #9: Add ability to apply scroll prompt to components
Add the ability for the scroll button to appear in components.  This would be useful when:

- Using a block / component to create a fake "page header."
- Applying to a mid-page, Text component that instructs people to "scroll down" to see more content.

### PR DESCRIPTION
**Pull request by swashbuck**
Fixes #9 

### Fix
* Add the ability for the scroll button to appear in blocks and components. Useful when using a Text component in lieu of a page header, such as when this 'page header' block is using the Video Background extension.
* Add a `margin-top` to prevent it from butting up against a `.component__widget`.
* Use ES6 syntax
* Use JSX template
* Improve documentation

### CODE REVIEW

File: js/adapt-scrollPrompt.js [hunk 1]
```diff
@@ -3,15 +3,26 @@ define([
...
     var model = view.model;
 
     var scrollPrompt = model.get('_scrollPrompt');
     if (!scrollPrompt || !scrollPrompt._isEnabled) return;
 
-    var modelType = model.get('_type');
-    if (modelType === 'course') modelType = 'menu';
+    var modelType;
+
+    switch (model.get("_type")) {
```
Comment (kirsty-hames) [inline js/adapt-scrollPrompt.js]: eslint reporting: strings must use single quotes (reported for all string instances)

File: js/adapt-scrollPrompt.js [hunk 2]
```diff
@@ -3,15 +3,26 @@ define([
   './scrollPromptView'
 ], function(Adapt, ScrollPromptView) {
 
-  Adapt.on('menuView:ready pageView:ready', function(view) {
+  Adapt.on('menuView:ready pageView:ready componentView:postRender', function(view) {
 
     var model = view.model;
```
Comment (kirsty-hames) [inline js/adapt-scrollPrompt.js]: eslint reporting: unexpected var, use let or const instead (reported for all instances of var)

File: README.md [hunk 3]
```diff
@@ -1,6 +1,6 @@
 # adapt-scrollPrompt
 
-A button which can be appended to menu and/or page headers.
+A button which can be appended to menu, page headers, and/or components.
```
Comment (kirsty-hames) [inline README.md]: In all instances, the button is appended to the header.

File: example.json [hunk 4]
```diff
@@ -1,5 +1,6 @@
   // apply to course.json for menu header
   // apply to contentObject.json for page header
+  // apply to components.json for component
```
Comment (kirsty-hames) [inline example.json]: In all instances, the button is appended to the header.
e.g `// apply to components.json for component header`

File: js/scrollPromptView.js [hunk 5]
```diff
@@ -31,12 +31,18 @@ define([
...
+      switch (this.model.get('_type')) {
+        case 'course':
+          Adapt.scrollTo('.js-children', { duration: 800 });
+          break;
+        case 'page':
+          Adapt.scrollTo('.article', { duration: 800 });
+          break;
+        case 'component':
+          var $nextBlock = this.$el.parents('.block').next();
+          Adapt.scrollTo($nextBlock, { duration: 800 });
```
Comment (kirsty-hames) [inline js/scrollPromptView.js]: Use `router.navigateToElement` instead of `Adapt.scrollTo` (deprecated).

Would you prefer this raised as a separate issue/PR seeing as this is the existing functionality and not specific to this PR?

**Review by kirsty-hames — COMMENTED** [review]
Hey @swashbuck, nice addition thanks. I've tested this on Mac Safari, Chrome, FF and iPhone and working as expected. Just a couple of thoughts on the implementation...

- At component level, the button is appended to the header so for components where no display text is set, the button isn't displayed (because there is no header).
- There's the potential to miss content if you select the scroll button as this displays before the component widget. I wonder if the scroll button should always come after the content?
- Although the default button position is aligned with the language direction we do often center scroll prompts. In the instance that a component isn't full width `("_layout": "full")` the positioning gets a bit more tricky if we do want to center to the course. Would a block level scroll button work better here or in addition?

File: example.json (hunk 4 above)
Comment (swashbuck) [reply example.json]: Done in [775b1b5](https://github.com/cgkineo/adapt-scrollPrompt/pull/4/commits/775b1b578626b42bcb85520f605a1a84f019cec5)

File: README.md (hunk 3 above)
Comment (swashbuck) [reply README.md]: Done in [775b1b5](https://github.com/cgkineo/adapt-scrollPrompt/pull/4/commits/775b1b578626b42bcb85520f605a1a84f019cec5)

File: js/adapt-scrollPrompt.js (hunk 1 above)
Comment (swashbuck) [reply js/adapt-scrollPrompt.js]: Apologies, this is a really old commit :)

Fixed in [775b1b5](https://github.com/cgkineo/adapt-scrollPrompt/pull/4/commits/775b1b578626b42bcb85520f605a1a84f019cec5)

File: js/adapt-scrollPrompt.js (hunk 2 above)
Comment (swashbuck) [reply js/adapt-scrollPrompt.js]: Fixed in [775b1b5](https://github.com/cgkineo/adapt-scrollPrompt/pull/4/commits/775b1b578626b42bcb85520f605a1a84f019cec5)

File: js/scrollPromptView.js (hunk 5 above)
Comment (swashbuck) [reply js/scrollPromptView.js]: Nope, this one's fine. Done in [775b1b5](https://github.com/cgkineo/adapt-scrollPrompt/pull/4/commits/775b1b578626b42bcb85520f605a1a84f019cec5)

**Comment by swashbuck** [comment]
>     * At component level, the button is appended to the header so for components where no display text is set, the button isn't displayed (because there is no header).
>     * There's the potential to miss content if you select the scroll button as this displays before the component widget. I wonder if the scroll button should always come after the content?

Sure, that makes sense.

>     * Although the default button position is aligned with the language direction we do often center scroll prompts. In the instance that a component isn't full width `("_layout": "full")` the positioning gets a bit more tricky if we do want to center to the course. Would a block level scroll button work better here or in addition?

What about just using `justify-content: center` on `.scrollPrompt__inner`? That element already uses `display: flex`. We could also make it a configurable option.

**Comment by kirsty-hames** [comment]
> What about just using `justify-content: center` on `.scrollPrompt__inner`? That element already uses `display: flex`. We could also make it a configurable option.

I do like the option to configure the button position and agree to using the existing `flex` properties. This is also consistent with how we already handle configurable layouts in [Vanilla](https://github.com/adaptlearning/adapt-contrib-vanilla/pull/364). 

Only supporting component and not block level though still means you can only position relative to your component container and not the block. e.g. you couldn't center the button to the center of the course if the button is configured on a half width component (unless you did some custom CSS). Maybe this is ok though and in this instance you should be using a full width component. I'm just being devil's advocate so happy to ignore if this is overkill :D

**Comment by kirsty-hames** [comment]
> I do like the option to configure the button position and agree to using the existing `flex` properties. This is also consistent with how we already handle configurable layouts in [Vanilla](https://github.com/adaptlearning/adapt-contrib-vanilla/pull/364).

Also I'm happy to raise this as a separate issue/PR as this is an additional request to the existing PR?

**Comment by swashbuck** [comment]
> Only supporting component and not block level though still means you can only position relative to your component container and not the block.

Apologies, I completely missed your point. I've added the ability to include the button in blocks.

> I do like the option to configure the button position and agree to using the existing flex properties.
> Also I'm happy to raise this as a separate issue/PR as this is an additional request to the existing PR?

Sure, would you mind raising this as a separate PR?

**Comment by swashbuck** [comment]
@kirsty-hames Also, I've converted this to ES6 syntax with a JSX template if you wouldn't mind having another look.

File: js/adapt-scrollPrompt.js [hunk 6]
```diff
@@ -1,25 +1,28 @@
...
 
-    var modelType = model.get('_type');
-    if (modelType === 'course') modelType = 'menu';
+    const scrollPrompt = model.get('_scrollPrompt');
+    if (!scrollPrompt || !scrollPrompt._isEnabled) return;
 
-    /* set model type selector to append scroll prompt to */
-    var modelTypeSelector = '.' + modelType + '__header-inner';
+    const modelType = model.get('_type');
+    const selector = modelType === 'component' ? '.component__inner' : `.${modelType}__header-inner`;
```
Comment (kirsty-hames) [inline js/adapt-scrollPrompt.js]: Should block level render to `.block__inner`? Otherwise we have the same issue we previously had with component where the button doesn't render if no display text is set (no block header is rendered).

File: templates/scrollPrompt.jsx [hunk 7]
```diff
@@ -0,0 +1,23 @@
...
+export default function ScrollPrompt (props) {
+  const {
+    _scrollPrompt,
+    onScrollPromptClick
+  } = props;
+
+  return (
+    <div className="scrollPrompt__inner a11y-ignore" aria-hidden="true">
+      <button className="btn-icon scrollPrompt__button" onClick={onScrollPromptClick}>
+        <div className="scrollPrompt__btn-icon">
```
Comment (kirsty-hames) [inline templates/scrollPrompt.jsx:13]: I'm happy to raise this as a separate PR as this might be out of scope for this but for consistency with other Adapt button icons I think we can lose `.scrollPrompt__btn-icon` so we just have the icon within the button. See below.
```
      <button className="btn-icon scrollPrompt__button" onClick={onScrollPromptClick}>
        <div className="icon" />
      </button>
```
Note, if making this change the CSS would also need updating to the following - [lines 9 - 11](https://github.com/swashbuck/adapt-scrollPrompt/blob/99777a3efe9f24c89e6f18a2190f6a8d0992152a/less/scrollPrompt.less#L9-L11).
```
  &__button .icon {
    .icon-controls-down;
  }
```

**Comment by kirsty-hames** [comment]
> > I do like the option to configure the button position and agree to using the existing flex properties.
> > Also I'm happy to raise this as a separate issue/PR as this is an additional request to the existing PR?
> 
> Sure, would you mind raising this as a separate PR?

PR raised https://github.com/cgkineo/adapt-scrollPrompt/issues/12

File: templates/scrollPrompt.jsx (hunk 7 above)
Comment (kirsty-hames) [reply templates/scrollPrompt.jsx:13]: ^ I've raised this as a new issue. See https://github.com/cgkineo/adapt-scrollPrompt/issues/13.

Comment (swashbuck) [reply templates/scrollPrompt.jsx:13]: Yep, agreed. Thanks for raising.

File: js/adapt-scrollPrompt.js (hunk 6 above)
Comment (swashbuck) [reply js/adapt-scrollPrompt.js]: @kirsty-hames Thanks for catching that. Here's what this looks like now:

block-level-inner

File: less/scrollPrompt.less [hunk 8]
```diff
@@ -15,4 +17,4 @@
       margin-right: 1em;
```
Comment (kirsty-hames) [inline less/scrollPrompt.less]: Typo, should be `1rem`?

**Review by kirsty-hames — APPROVED** [review]
I've raised a comment for a typo but otherwise working as expected thanks :)

File: less/scrollPrompt.less (hunk 8 above)
Comment (swashbuck) [reply less/scrollPrompt.less]: Fixed :)

**Review by kirsty-hames — APPROVED** [review]

**Comment by kirsty-hames** [comment]
Prior to the margin typo commit, I tested this on Mac Safari, Chrome, FF and iPhone. Based on Monday's call I think we agreed you only need one other person to review and approve a CGKineo PR so if you're happy with this I think we're good to merge @swashbuck?
